# .readthedocs.yml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

python:
  install:
    - method: pip
      path: .                   # pip install -e .
    - requirements: docs/requirements.txt

sphinx:
  # path to your conf.py
  configuration: docs/conf.py
